---
title: "Soybean Acres Harvested in Virginia"
author: "Billy Stoneman and Kealyn Greenwell"
date: ""
output:
  html_document: 
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(wooldridge); library(ggplot2); library(dplyr); library(stargazer); library(patchwork); library(stringr); library(readxl); library(ggthemes); library(tidyr); library(fpp3); library(scales); library(tidyUSDA); library(sf);library(leaflet); library(htmltools); library(knitr); library(kableExtra)
```

```{r data read, include = FALSE}
#change directory as needed

#change directory as needed

# URL of the raw ZIP file on GitHub
zip_url <- "https://github.com/Kealyn8/soybeans/raw/main/va_shp.zip"

# Download the ZIP file to a temporary location
temp_file <- tempfile(fileext = ".zip")
download.file(zip_url, temp_file)

# Unzip the file to a temporary directory
unzip_dir <- tempfile()  # Create a temporary directory to unzip the file
unzip(temp_file, exdir = unzip_dir)

# List the contents of the unzipped folder (optional)
unzipped_files <- list.files(unzip_dir, recursive = TRUE)
print(unzipped_files)

# Check if there's a subfolder or if the shapefile is in a folder
# Assuming the shapefile inside the ZIP is in a folder called 'va_shp' and named 'va_shp.shp'
shapefile_path <- file.path(unzip_dir, "va_shp", "va_counties.shp")

count <- st_read(shapefile_path) %>% select(NAME, geometry)
```


```{r Map, echo = FALSE, out.width='100%', out.height='600px'}

key <- "24C319CF-223E-3DE5-A431-6077153BC7CB"

quick1 <- getQuickstat(
  key = key,
  program = NULL,
  data_item = "SOYBEANS - ACRES HARVESTED",
  sector = "CROPS",
  group = "FIELD CROPS",
  commodity = "SOYBEANS",
  category = "AREA HARVESTED",
  domain = NULL,
  geographic_level = "COUNTY",
  state = "VIRGINIA",
  county = NULL,
  year = as.character(2001:2024),
  geometry = FALSE,
  lower48 = FALSE,
  weighted_by_area = FALSE
)



soycounties <- quick1 %>% select(year, Value, county_name) %>% rename(NAME = county_name) 
soycounties <- dplyr::arrange(soycounties, desc(year)) 
soycounties$Value <- ifelse(is.na(soycounties$Value), 0, soycounties$Value) #changing NA values to 0
soycounties$NAME <- str_to_title(soycounties$NAME)
soycounties <- soycounties %>%
  filter(!str_detect(NAME, fixed("city", ignore_case = TRUE))) %>%  # Exclude rows with "city"
  filter(!str_detect(NAME, fixed("other", ignore_case = TRUE)))   # Exclude rows with "other"


#2023 ONLY, eventually want 2000-present

data <- soycounties %>% filter(year == 2023)

#sorting out data... by county name and renaming to fit given code
count <- count %>% left_join(data, by = "NAME") 
count$Soybeans <- count$Value #create new column to fit existing code
count$Soybeans <- ifelse(is.na(count$Soybeans), 0, count$Soybeans) #changing NA values to 0

#lines 60 and 65 give errors and I am not sure why

#changing the empty year values to 2023
count$year <- ifelse(is.na(count$year), 2023, count$year) 

#these are the locations for the crushing mills, grain elevators, and lego

locations <- as.data.frame(cbind(c('Perdue Grain and Oilseed', 'Perdue AgriBusiness - Bainbridge Grain Elevator and Oilseed Crush', 'Perdue Grain and Oilseed, LLC. (NC)', 'Cargill, Inc.', 'Perdue Grain and Oilseed, LLC.(MD)',
                                   'Perdue Agribusiness Kinsale', 'Perdue Agribusiness Kilmarnock','Perdue Agribusiness Tappahannock', 'Mennel Milling West Point',
                                   'Scoular Port of Richmond', 'Scoular Weyers Cave', 'Scoular Windsor', 'Smithfield Grain Petersburg', 'Wakefield Farm Service', 'Meherrin Grain Franklin',
                                   'Meherrin Grain Capron', 'Meherrin Grain Charlotte Courthouse', 'Meherrin Grain Newsomes', 'Keystone Grain', 'Augusta Co-op Farm Bureau, Inc. Staunton',
                                   'Rockingham Co-op Dayton', 'Culpeper Farmers Co-op', 'Lego Facility', 'DeLong Facility'),
                                 c('Crush Plant', 'Crush Plant', 'Crush Plant', 'Crush Plant', 'Crush Plant', 'Grain Elevator','Grain Elevator','Grain Elevator','Grain Elevator','Grain Elevator','Grain Elevator',
                                   'Grain Elevator','Grain Elevator', 'Grain Elevator', 'Grain Elevator','Grain Elevator','Grain Elevator','Grain Elevator','Grain Elevator','Grain Elevator','Grain Elevator','Grain Elevator',
                                   'Additional Facility', 'Additional Facility'),
                                 c(36.8036684, 40.0729735, 36.36438272, 35.0865324, 38.38468454, 38.0303092, 37.7005569,37.9177046,37.5506807,37.4565925,38.2808153, 36.8099991, 37.1980703, 36.9732506, 36.660653, 36.706100, 37.133065, 36.6302446, 36.6862312, 38.1347458, 38.423984, 38.4826347, 37.31111830508404, 36.8354),
                                 c(-76.28722583, -76.6365597, -76.89787336, -78.84710742, -75.52773315, -76.5756774,-76.3522586,-76.854209, -76.8157385, -77.4225141, -78.9286916, -76.7470809, -77.4352446,  -76.9905024, -76.975516, -77.200142, -78.720856, -77.1096605, -78.9032562, -79.0425081, -78.9228, -77.9716346, -77.38178760354225, -76.2983),
                                 c(27, 17.5, 13, 'N/A', 22, 'N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A','N/A', 'N/A','N/A')))


colnames(locations) <- c('Place', 'Type', 'lat', 'lng', 'Capacity')

capacities <- as.data.frame(cbind(c('Perdue Grain and Oilseed', 'Perdue AgriBusiness - Bainbridge Grain Elevator and Oilseed Crush', 'Perdue Grain and Oilseed, LLC. (NC)', 'Cargill, Inc.', 'Perdue Grain and Oilseed, LLC.(MD)'),
                                  c(27, 17.5, 13, 'N/A', 22)))
colnames(capacities) <- c('Plant', 'Cap')

# Convert locations into a spatial data frame so that it can be plotted

locations <- st_as_sf(locations, coords = c('lng', 'lat'), crs = st_crs(count))

#transforming sf to WGS84
locations <- st_transform(locations, crs = 4326)
count$geometry <- st_transform(count$geometry, crs = 4326)

# Defining the color scheme for filling in counties - you can make significant alterations to this if you want

pal <- colorNumeric(palette = c('white', 'orange', 'red4'), domain = count$Soybeans)

# This code chunk makes the title bold and centered and stay in place when you zoom in/out -- nothing needs to change

tag.map.title <- tags$style(HTML("
  .leaflet-control.map-title { 
    transform: translate(-50%,20%);
    position: fixed !important;
    left: 50%;
    text-align: center;
    padding-left: 10px; 
    padding-right: 10px; 
    background: rgba(255,255,255,0.75);
    font-weight: bold;
    font-size: 28px;
  }
"))

title <- tags$div(tag.map.title, HTML('Soybeans Harvested'))

# Making a leaflet

leaflet(count$geometry) %>% addTiles() %>% # This line tells it what data to use for the county colors / soybean data
  addPolygons(weight = 1.0, smoothFactor = 1.0, opacity = 1.0, fillOpacity = 1.0, color = 'black', fillColor = pal(count$Soybeans), label = lapply(paste(count$NAME, '<br>', count$Soybeans, 'Acres Harvested'), HTML)) %>% # This plots the soybean data
  
  addCircleMarkers(data = locations[which(locations$Type == 'Crush Plant'),], group = 'Crush Plant', color = "darkgreen", fillColor = "darkgreen", fillOpacity = 1, radius = 4, label = lapply(paste(capacities$Plant, '<br>', capacities$Cap, 'Million bu per Year'), HTML)) %>% # This line add the locations of the processing facilities for one type
  
  addCircleMarkers(data = locations[which(locations$Type == 'Grain Elevator'),], group = 'Grain Elevator', color = "darkblue", fillColor = "darkblue", fillOpacity = 1, radius = 4, label = lapply(paste(locations$Place), HTML)) %>% # This line add the locations of the processing facilities for a second type
  
  addCircleMarkers(data = locations[which(locations$Type == 'Additional Facility'),], group = 'Additional Facility', color = "yellow", fillColor = "yellow", fillOpacity = 1, radius = 4, label = lapply(paste(locations$Place), HTML)) %>% 
  
  addProviderTiles('Esri.WorldGrayCanvas') %>% # This renders a plain background outside of your geometry
  
  addLegend(position = 'topright', pal = pal, values = count$Soybeans, title = 'Soybeans Harvested <br> acres', opacity = 1) %>% # This adds a legend
  
  addLegend(position = 'bottomright',                       #this is the legend for the circle markers
            colors = c("darkgreen", "darkblue", "yellow"), 
            labels = c("Crush Plant", "Grain Elevator", "Additional Facilities"), 
            title = "Processing Facilities",
            opacity = 1) %>%
  
  addLayersControl(data = locations, overlayGroups = c('Crush Plant', 'Grain Elevator', 'Additional Facility'), options = layersControlOptions(collapsed = FALSE))

```

